### ISSUE TITLE
Error and wrong output

### ISSUE THREAD

**Issue by andy29485** [DHS-Computer-Science/uva-hspc-practice-2012-00-LordMilton#1]
Your code generates an exception:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
    at StudentNames.main(StudentNames.java:16)
```

Also, if the exception if fixed, the names is the output are First, Last instead of Last, First
Your output:

```
Case 1: Tyler, Lopez
Case 2: Alexandra, Johnson
Case 3: Martin, Young
Case 4: Sabrina, Chao
Case 5: Arjun, Gupta
```

What it should be:

```
Case 1: Lopez, Tyler
Case 2: Johnson, Alexandra
Case 3: Young, Martin
Case 4: Chao, Sabrina
Case 5: Gupta, Arjun
```

![Fix](http://puu.sh/lTarI/70ebc7bca9.png)

**Comment by LordMilton** [comment]
What's most irritating about this, is that while coding on Github, one
cannot see the problem description, that's probably why I had the names
backwards.

**Comment by andy29485** [comment]
You shouldn't be coding on github...

How about this: I'll give you a quick explanation on what git is and how to
use it on Wednesday. Until then don't worry about it. And if you still
don't like/see no point in it after Wednesday, forget about git.

**Comment by andy29485** [comment]
Note: I'll use the GUI for the explanation(unless you want to learn the command line interface).
